project:
  type: website

website:
  title: "FIFA CONFEDERATIONS"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/DhruvNirmal
      - icon: linkedin
        href: https://www.linkedin.com/feed/
format:
  html:
    theme: superhero
    css: styles.css



